### PR TITLE
Feature/#5

### PR DESCRIPTION
**Pull request by spyhunter99**
Lots of changes, that are primarily to shuffle classes around to support on device testing with maven. Unfortunately, this requires a multi-module project and the application of the maven android plugin.

To build on your machine, 

- you'll need to have the android sdk installed and updated to at least api 23
- do the following once (it's a run once then never have to again)
`
git clone https://github.com/simpligility/maven-android-sdk-deployer
cd maven-android-sdk-deployer
mvn clean install -fn -B -U
`

- Then run `mvn clean install` from the checkout location of SQLDroid with a device attached. Due to some strangeness with the maven android plugin, you may have to attempt the build up to 3 times to get an initial success.

The only other alternative is to convert the project to gradle, which i can help with as well

This PR also includes alterations to the travis build file to automate testing on API8 + devices. It pretty much renders the build process using rake unnecessary and thus it was removed.

### CODE REVIEW

**Comment by ergouser** [comment]
spyhunter99,

What happened to the compatibility layer?  This allows SQLDroid to 
provide a JDBC interface on any non-Android platform using JNA.  I use 
it in production on both Linux and Windows and it allows use to use 
SQLDroid as one solution whether deploying to Android, Windows, Linux, 
etc. etc.

Thanks,

Jim


On 05/01/2016 08:03 AM, spyhunter99 wrote:
>
> Lots of changes, that are primarily to shuffle classes around to 
> support on device testing with maven. Unfortunately, this requires a 
> multi-module project and the application of the maven android plugin.
>
> To build on your machine,
>
>   * you'll need to have the android sdk installed and updated to at
>     least api 23
>  *
>
>     do the following once (it's a run once then never have to again)
>     |
>     git clone https://github.com/simpligility/maven-android-sdk-deployer
>     cd maven-android-sdk-deployer
>     mvn clean install -fn -B -U
>     |
>
>  *
>
>     Then run |mvn clean install| from the checkout location of
>     SQLDroid with a device attached. Due to some strangeness with the
>     maven android plugin, you may have to attempt the build up to 3
>     times to get an initial success.
>
> The only other alternative is to convert the project to gradle, which 
> i can help with as well
>
> This PR also includes alterations to the travis build file to automate 
> testing on API8 + devices. It pretty much renders the build process 
> using rake unnecessary and thus it was removed.
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/SQLDroid/SQLDroid/pull/59
>
>
>         Commit Summary
>
>   * #5 mavenizing the unit tests to run on device
>   * #5 tricking travis to build this
>   * #5 fix for several tests related to null/empty result sets select
>     statements
>   * #5 resolves the remaining unit tests on android devices
>   * #5 clean up aisle 5
>   * #5 whitespace clean up
>   * #5 not sure how i did that one
>   * #5 setting the min sdks lower for the test project
>   * #5 travis fixes
>   * #5 travis fix
>
>
>         File Changes
>
>   * *M* .gitignore
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-0> (2)
>   * *M* .travis.yml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-1> (93)
>   * *D* Gemfile
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-2> (4)
>   * *D* Gemfile.lock
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-3> (14)
>   * *D* Rakefile
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-4> (63)
>   * *D* Rakefile_windows
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-5> (53)
>   * *D* compat/android/content/ContentValues.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-6> (11)
>   * *D* compat/android/database/AbstractCursor.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-7> (192)
>   * *D* compat/android/database/Cursor.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-8> (69)
>   * *D* compat/android/database/MatrixCursor.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-9> (178)
>   * *D* compat/android/database/MergeCursor.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-10> (294)
>   * *D* compat/android/database/SQLException.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-11> (16)
>   * *D* compat/android/database/SQLite.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-12> (114)
>   * *D* compat/android/database/sqlite/SQLiteDatabase.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-13> (168)
>   * *D*
>     compat/android/database/sqlite/SQLiteDatabaseLockedException.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-14> (17)
>   * *D* compat/android/database/sqlite/SQLiteException.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-15> (17)
>   * *D* compat/android/util/Log.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-16> (33)
>   * *D* lib/sqldroid.rb
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-17> (6)
>   * *D* lib/sqldroid/version.rb
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-18> (3)
>   * *M* pom.xml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-19> (102)
>   * *A* sqldroid-it/pom.xml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-20> (63)
>   * *R* sqldroid-it/src/main/AndroidManifest.xml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-21> (6)
>   * *R* sqldroid-it/src/main/java/org/sqldroid/DriverUnitTest.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-22> (16)
>   * *D* sqldroid.gemspec
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-23> (23)
>   * *A* sqldroid/pom.xml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-24> (41)
>   * *R* sqldroid/src/main/AndroidManifest.xml
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-25> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/DebugPrinter.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-26> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/DroidDataSource.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-27> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/Log.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-28> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidBlob.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-29> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidClob.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-30> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidConnection.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-31> (0)
>   * *R*
>     sqldroid/src/main/java/org/sqldroid/SQLDroidDatabaseMetaData.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-32> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidDriver.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-33> (0)
>   * *R*
>     sqldroid/src/main/java/org/sqldroid/SQLDroidPreparedStatement.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-34> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidResultSet.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-35> (0)
>   * *R*
>     sqldroid/src/main/java/org/sqldroid/SQLDroidResultSetMetaData.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-36> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidSQLException.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-37> (0)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLDroidStatement.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-38> (2)
>   * *R* sqldroid/src/main/java/org/sqldroid/SQLiteDatabase.java
>     <https://github.com/SQLDroid/SQLDroid/pull/59/files#diff-39> (0)
>
>
>         Patch Links:
>
>   * https://github.com/SQLDroid/SQLDroid/pull/59.patch
>   * https://github.com/SQLDroid/SQLDroid/pull/59.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SQLDroid/SQLDroid/pull/59>
>

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by spyhunter99** [comment]
I didn't see it referenced anywhere in the code. Also, there's xerial's setup, a cross platformm jdbc driver for sqlite (everything but android). I can revert the commits, but I don't understand how it should be rigged into the build.

**Comment by ergouser** [comment]
spyhunter99,

It's a separate jar, formerly named "SqldroidAndroidCompat.jar" (or 
something similar).  You can add it to any project (along with the JNA 
jar and the Sqlite dll) and use the SQLDroid jar from other platforms.  
It means that you can test application on a JDK before deploying, or 
just use SQLDroid as a JDBC driver for Windows (which we do all the 
time).  I haven't looked at the Xerial code in a while.  At the time the 
compatibility was created it was missing key features (blobs being one 
at the time), but I'm not really interested in changing drivers or 
figuring out the idiosyncrasies of two JBDC drivers when SQLDroid does 
the job everywhere.

Not sure if that helps answer your question, feel free to ask more if not.

Thanks,

Jim


On 05/01/2016 11:02 AM, spyhunter99 wrote:
>
> I didn't see it referenced anywhere in the code. Also, there's 
> xerial's setup, a cross platformm jdbc driver for sqlite (everything 
> but android). I can revert the commits, but I don't understand how it 
> should be rigged into the build.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SQLDroid/SQLDroid/pull/59#issuecomment-216055524>
>

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by spyhunter99** [comment]
Alright, give me a few

**Comment by spyhunter99** [comment]
Where do i get the native libraries for sqlite3? i only see executables. xerial uses JNI so I don't think i can use those artifacts.

**Comment by ergouser** [comment]
There's part of the SQLite download:

https://www.sqlite.org/download.html

On 05/01/2016 12:04 PM, spyhunter99 wrote:
>
> Where do i get the native libraries for sqlite3? i only see 
> executables. xerial uses JNI so I don't think i can use those artifacts.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SQLDroid/SQLDroid/pull/59#issuecomment-216059468>
>

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by spyhunter99** [comment]
oh i know the site, but it only has downloads for executables, not .so or .dll files. I'm slightly unfamiliar with JNA, but is that what we need? I thought we need a .so or .dll file? And where does it go?

**Comment by ergouser** [comment]
The dlls for Windows are at that link 
(https://www.sqlite.org/download.html):

*Precompiled Binaries for Windows

*https://www.sqlite.org/2016/sqlite-dll-win64-x64-3120200.zip
https://www.sqlite.org/2016/sqlite-dll-win32-x86-3120200.zip

The .so seems to end up in linux distros.  This is where it ended up on 
my system (I think that there's more than one copy around).

-rw-r--r-- 1 root root 754880 Jul 15  2015 
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6

I've never tried it on a Mac, but there should be .so somewhere for 
that. I think that firefox uses SQLite on all platforms.


On 05/01/2016 04:22 PM, spyhunter99 wrote:
>
> oh i know the site, but it only has downloads for executables, not .so 
> or .dll files. I'm slightly unfamiliar with JNA, but is that what we 
> need? I thought we need a .so or .dll file? And where does it go?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SQLDroid/SQLDroid/pull/59#issuecomment-216076806>
>

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by donv** [comment]
Unless I missed something, this PR does not offer a way to build the RubyGem.  We still need that.

**Pull request closed without merging**
