### PR TITLE
Robolectric tests

### PR DESCRIPTION
**Pull request by jhannes**
The current DriverUnitTest doesn't seem to run from IDEs or with `mvn test`. By using Robolectric, it's possible to get a pretty smooth test running approach.

This pull request contains:

* Changes to the pom to allow Robolectric to run: inclusion of the Robolectric dependency and a change to use ANDROID_HOME instead of Maven for android.jar
* pom.xml includes AssertJ and upgrades to Java 1.7 to allow for a more fluent test style
* A modified version of DriverUnitTest that uses Robolectric
* An example of a unit test that uses Robolectric, Java 1.7 and AssertJ
* An alternative implementation of the same test that uses a few test helper methods
* Changes to Connection, PreparedStatement and ResultSet which implements RETURN_GENERATED_KEYS, setDate and getDate and the tests to prove it.

### CODE REVIEW

**Comment by jhannes** [comment]
It seems like this commit fails on travis because it doesn't have write access to the right path in the file system. Fixing it now...

**Comment by jhannes** [comment]
Aaaaand... Unit tests running on Travis-CI

**Comment by donv** [comment]
Woohoo!  Merging!

**Comment by donv** [comment]
@jhannes Will this compile for use with older Android versions than 21?

**Comment by jhannes** [comment]
@donv This change uses android-21 in pom.xml and will not work without it. I think Robolectric works all the way back to android-16. I'll attempt to use this version instead.

src/main/java has been modified in any way that's incompatible with older version.

**Comment by donv** [comment]
android-16 would be fine.  I have one customer on android-15, even.

**Comment by jhannes** [comment]
Ok - did some checking: android-21 is required to run Robolectric tests, but older versions can be used to build. However: Robolectric lets us specify which version of Android the tests should be valid for:

  @Config(sdk = Build.VERSION_CODES.KITKAT)

Do you need the code to build with android-15 (in that case, we need a profile), or is it enough that the jar can be used under android-15?

**Comment by donv** [comment]
It is enough that the JAR can be used with android-15.  The rest of the test/build process does not matter to me.

**Pull request merged**
